// This code was generated by raptor mini in GitHub Copilot.
import { describe, expect, it } from 'vitest'
import { axe } from 'vitest-axe'
import pane from '../../src/contactsPane'
import type Search from '../../src/components/search'
import { sym, parse } from 'rdflib'
import { store } from 'solid-logic'
import { context, doc, prefixes, web } from './setup'

// ensure the store knows this is an AddressBook so asyncRender will build UI

const base = doc.dir()?.uri || ''
const book = sym(base + 'book.ttl#this')

web[base + 'book.ttl'] = `
<#this> a vcard:AddressBook;
    vcard:fn "Test address book".
`
for (const uri in web) {
  parse(prefixes + web[uri], store, uri)
}

describe('contacts-pane accessibility', () => {
  it('renders an empty UI of an address book', async () => {
    const div = pane.render(book, context)
    expect(div.classList.contains('contactPane')).toBe(true)
    expect(div.innerHTML).toMatch('')
    expect(div.dataset.paneWidth).toBeDefined()
    expect(div.dataset.paneNarrow).toBeDefined()
    expect(div.dataset.viewportNarrow).toBeDefined()
    // check accessibility of the generated DOM (ignore aria-allowed-role for now)
    const axeResults = await axe(div, { rules: { 'aria-allowed-role': { enabled: false } } })
    expect(axeResults.violations).toHaveLength(0)
  })

  it('includes a clear button in the search component and it works', async () => {
    const div = pane.render(book, context)
    // Lit components only render once connected, so the pane must be in the
    // document -- unlike the old imperative markup, which existed detached.
    document.body.appendChild(div)
    // let asyncRender finish (it runs in a microtask)
    await new Promise(resolve => setTimeout(resolve, 0))
    const search = div.querySelector('contacts-pane-search') as Search
    expect(search).toBeTruthy()
    await search.updateComplete
    const solidInput = search.shadowRoot!.querySelector('solid-ui-input') as HTMLElement & { updateComplete: Promise<boolean> }
    expect(solidInput).toBeTruthy()
    await solidInput.updateComplete
    const input = solidInput.shadowRoot!.querySelector('input') as HTMLInputElement
    expect(input).toBeTruthy()
    // no clear button until there is text
    expect(search.shadowRoot!.querySelector('button')).toBeNull()
    // simulate typing
    input.value = 'hello'
    input.dispatchEvent(new Event('input'))
    await solidInput.updateComplete
    await search.updateComplete
    expect(search.value).toBe('hello')
    const clear = search.shadowRoot!.querySelector('button') as HTMLElement
    expect(clear).toBeTruthy()
    // clicking clear should reset the text and remove the button again
    clear.click()
    await search.updateComplete
    expect(search.value).toBe('')
    expect(search.shadowRoot!.querySelector('button')).toBeNull()
    // run axe check on the full pane container after interactivity
    const axeResults = await axe(div, { rules: { 'aria-allowed-role': { enabled: false } } })
    expect(axeResults.violations).toHaveLength(0)
    div.remove()
  })
})
